apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site-deployment
  labels:
    app: personal-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
    spec:
      containers:
      - name: personal-site-container
        image: imshashannk/personal-site:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
